# Generated by Django 3.0.5 on 2024-05-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
